### ISSUE TITLE
源码有问题大哥，

### ISSUE THREAD

**Issue by Lq0ne** [iamywang/Campus-Guide-System#4]
![image](https://github.com/iamywang/Campus-Guide-System/assets/52685569/3763f495-2c99-4210-83c2-4c8a72f2c454)

**Comment by iamywang** [comment]
你好，这个问题是这样的，main_console.cpp这个文件是一开始控制台版本的main函数，后面换成GUI后又改了一些内容就没管。

你把这个文件直接删掉，然后把.pro里加上QT+=widgets就可以了。

```
$ rm main_console.cpp
$ qmake -project
$ qmake Campus-xxxx.pro
$ make
```
